version: '3.5'

services:
  laravel:
    image: leonardoncintra/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: leonardoncintra/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
