apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: "leonardoncintra/hellojs:v6.3"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
