apiVersion: v1
kind: Service
metadata:
  name: nodeserver-service
spec:
  selector:
    app: nodeserver
  type: ClusterIP #usar LoadBalancer para acesso externo (front end)
  ports:
    - name: nodeserver-service-port
      port: 3000
      protocol: TCP
#F0096